### ISSUE TITLE
Selecting a value from a Select dropdown results in a reporting error

### ISSUE THREAD

**Issue by basdijkstra** [testproject-io/csharp-sdk#57]
When I execute the following line in a test:

```csharp
new SelectElement(this.driver.FindElement(By.CssSelector("#country"))).SelectByText("Australia");
```
I see an error message in the log:

`2021-01-15 15:53:22.6015 | ERROR | TestProject.OpenSDK.Internal.ReportsQueue | Agent returned HTTP 500 with message:`

indicating that there's an error in the DriverCommandReport that's being sent to the Agent. Apparently it doesn't like the `findChildElements` driver command.. This should be fixed as it results in reports not being sent to TestProject.

**Comment by mstrelex** [comment]
@basdijkstra `result` for `findChildElements` should be an Array and not a JSON object.
We will handle it and fail gracefully but in order to make it work, data structure sent should be adjusted.

**Comment by basdijkstra** [comment]
Thanks, that helps. I see what's going wrong now and will fix it.

**Comment by basdijkstra** [comment]
As the PR containing the fix for this issue has been merged, I'm closing this issue.
