### ISSUE TITLE
Capabilities are ignored

### ISSUE THREAD

**Issue by Rantzur1992** [testproject-io/csharp-sdk#61]
Test:

```
        [SetUp]
        public void SetUp()
        {
            var options = new OpenQA.Selenium.Chrome.ChromeOptions();
            options.AddArguments("headless");
            driver = new ChromeDriver(chromeOptions: options, jobName: "NUNit Tests", projectName: "C# Open SDK Tests");
        }

        [Test]
        public void TestSomethingTest_1()
        {
            driver.Navigate().GoToUrl("https://example.testproject.io");
            driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            driver.FindElement(By.CssSelector("#login")).Click();
            Assert.IsTrue(driver.FindElement(By.CssSelector("#greetings")).Displayed);
        }
```

Capabilities are ignored, and it will not launch chrome headless.
chrome driver logs show:
![image](https://user-images.githubusercontent.com/6703682/104836963-31f17080-58ba-11eb-8b4c-f27c54c739f3.png)

Just for reference, on Java, it works, and it looks like so:
![image](https://user-images.githubusercontent.com/6703682/104836970-3b7ad880-58ba-11eb-9dc2-a0c0b56bf29d.png)

**Comment by basdijkstra** [comment]
I've just submitted #65, which addresses this issue. Once it has been merged, you should be able to retest it with the latest published version, @Rantzur1992 .

**Comment by basdijkstra** [comment]
Since #65 has now been merged, you should be able to retest this with the latest pre-release version, @Rantzur1992.

**Comment by Rantzur1992** [comment]
Verified in the latest version.
Closing.

**Comment by Rantzur1992** [comment]
@basdijkstra  This works only in Chrome, on FireFox it is still ignored.

**Comment by basdijkstra** [comment]
No it's not, at least not here:

```csharp
OpenQA.Selenium.Firefox.FirefoxOptions options = new OpenQA.Selenium.Firefox.FirefoxOptions();
options.AddArgument("-headless");
this.driver = new FirefoxDriver(firefoxOptions: options);
```

Don't forget the dash in `-headless`, the Firefox argument is different from the Chrome one.

**Comment by Rantzur1992** [comment]
Oh google confused me on that one, thanks.
